namespace hex {
    partial class FormTest2 {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormTest2));
            this.panel1 = new System.Windows.Forms.Panel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.lblByte = new System.Windows.Forms.Label();
            this.lblInt32 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.lblUint16 = new System.Windows.Forms.Label();
            this.lblInt16 = new System.Windows.Forms.Label();
            this.lblUint32 = new System.Windows.Forms.Label();
            this.lblFloat = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.hex21 = new hex.Hex2();
            this.panel1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.tableLayoutPanel1);
            this.panel1.Controls.Add(this.label7);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel1.Location = new System.Drawing.Point(543, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(193, 343);
            this.panel1.TabIndex = 1;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.InsetDouble;
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27.89474F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 72.10526F));
            this.tableLayoutPanel1.Controls.Add(this.label6, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.label5, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.label4, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.label3, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.label2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.lblByte, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.lblInt32, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.lblUint16, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.lblInt16, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.lblUint32, 1, 3);
            this.tableLayoutPanel1.Controls.Add(this.lblFloat, 1, 5);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 20);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 6;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(193, 130);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(6, 108);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(30, 13);
            this.label6.TabIndex = 16;
            this.label6.Text = "Float";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(6, 87);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(31, 13);
            this.label5.TabIndex = 15;
            this.label5.Text = "Int32";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(6, 66);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(39, 13);
            this.label4.TabIndex = 14;
            this.label4.Text = "UInt32";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(6, 45);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(31, 13);
            this.label3.TabIndex = 13;
            this.label3.Text = "Int16";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(6, 24);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(39, 13);
            this.label2.TabIndex = 12;
            this.label2.Text = "UInt16";
            // 
            // lblByte
            // 
            this.lblByte.BackColor = System.Drawing.SystemColors.Control;
            this.lblByte.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblByte.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblByte.ForeColor = System.Drawing.Color.Black;
            this.lblByte.Location = new System.Drawing.Point(60, 3);
            this.lblByte.Name = "lblByte";
            this.lblByte.Size = new System.Drawing.Size(127, 18);
            this.lblByte.TabIndex = 2;
            this.lblByte.Text = "Byte";
            // 
            // lblInt32
            // 
            this.lblInt32.BackColor = System.Drawing.SystemColors.Control;
            this.lblInt32.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInt32.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblInt32.ForeColor = System.Drawing.Color.Black;
            this.lblInt32.Location = new System.Drawing.Point(60, 87);
            this.lblInt32.Name = "lblInt32";
            this.lblInt32.Size = new System.Drawing.Size(127, 18);
            this.lblInt32.TabIndex = 9;
            this.lblInt32.Text = "Byte";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(6, 3);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(28, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Byte";
            // 
            // lblUint16
            // 
            this.lblUint16.BackColor = System.Drawing.SystemColors.Control;
            this.lblUint16.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUint16.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUint16.ForeColor = System.Drawing.Color.Black;
            this.lblUint16.Location = new System.Drawing.Point(60, 24);
            this.lblUint16.Name = "lblUint16";
            this.lblUint16.Size = new System.Drawing.Size(127, 18);
            this.lblUint16.TabIndex = 4;
            this.lblUint16.Text = "Byte";
            // 
            // lblInt16
            // 
            this.lblInt16.BackColor = System.Drawing.SystemColors.Control;
            this.lblInt16.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInt16.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblInt16.ForeColor = System.Drawing.Color.Black;
            this.lblInt16.Location = new System.Drawing.Point(60, 45);
            this.lblInt16.Name = "lblInt16";
            this.lblInt16.Size = new System.Drawing.Size(127, 18);
            this.lblInt16.TabIndex = 5;
            this.lblInt16.Text = "Byte";
            // 
            // lblUint32
            // 
            this.lblUint32.BackColor = System.Drawing.SystemColors.Control;
            this.lblUint32.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUint32.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUint32.ForeColor = System.Drawing.Color.Black;
            this.lblUint32.Location = new System.Drawing.Point(60, 66);
            this.lblUint32.Name = "lblUint32";
            this.lblUint32.Size = new System.Drawing.Size(127, 18);
            this.lblUint32.TabIndex = 7;
            this.lblUint32.Text = "Byte";
            // 
            // lblFloat
            // 
            this.lblFloat.BackColor = System.Drawing.SystemColors.Control;
            this.lblFloat.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFloat.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFloat.ForeColor = System.Drawing.Color.Black;
            this.lblFloat.Location = new System.Drawing.Point(60, 108);
            this.lblFloat.Name = "lblFloat";
            this.lblFloat.Size = new System.Drawing.Size(127, 19);
            this.lblFloat.TabIndex = 11;
            this.lblFloat.Text = "Byte";
            // 
            // label7
            // 
            this.label7.BackColor = System.Drawing.Color.LightGray;
            this.label7.Dock = System.Windows.Forms.DockStyle.Top;
            this.label7.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Black;
            this.label7.Location = new System.Drawing.Point(0, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(193, 20);
            this.label7.TabIndex = 10;
            this.label7.Text = "Data inspector";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // hex21
            // 
            this.hex21.AsciiSelected = false;
            this.hex21.BackColor = System.Drawing.Color.White;
            this.hex21.Data = new byte[] {
        ((byte)(255)),
        ((byte)(11)),
        ((byte)(69)),
        ((byte)(123)),
        ((byte)(167)),
        ((byte)(152)),
        ((byte)(175)),
        ((byte)(40)),
        ((byte)(38)),
        ((byte)(112)),
        ((byte)(237)),
        ((byte)(56)),
        ((byte)(182)),
        ((byte)(232)),
        ((byte)(188)),
        ((byte)(231)),
        ((byte)(206)),
        ((byte)(91)),
        ((byte)(99)),
        ((byte)(12)),
        ((byte)(196)),
        ((byte)(150)),
        ((byte)(52)),
        ((byte)(128)),
        ((byte)(172)),
        ((byte)(209)),
        ((byte)(229)),
        ((byte)(120)),
        ((byte)(179)),
        ((byte)(55)),
        ((byte)(106)),
        ((byte)(171)),
        ((byte)(19)),
        ((byte)(105)),
        ((byte)(182)),
        ((byte)(243)),
        ((byte)(74)),
        ((byte)(8)),
        ((byte)(243)),
        ((byte)(86)),
        ((byte)(3)),
        ((byte)(51)),
        ((byte)(126)),
        ((byte)(32)),
        ((byte)(161)),
        ((byte)(229)),
        ((byte)(61)),
        ((byte)(118)),
        ((byte)(163)),
        ((byte)(40)),
        ((byte)(34)),
        ((byte)(142)),
        ((byte)(182)),
        ((byte)(244)),
        ((byte)(32)),
        ((byte)(105)),
        ((byte)(215)),
        ((byte)(196)),
        ((byte)(206)),
        ((byte)(213)),
        ((byte)(178)),
        ((byte)(55)),
        ((byte)(116)),
        ((byte)(239)),
        ((byte)(5)),
        ((byte)(65)),
        ((byte)(37)),
        ((byte)(76)),
        ((byte)(50)),
        ((byte)(200)),
        ((byte)(157)),
        ((byte)(198)),
        ((byte)(104)),
        ((byte)(12)),
        ((byte)(8)),
        ((byte)(145)),
        ((byte)(23)),
        ((byte)(19)),
        ((byte)(222)),
        ((byte)(199)),
        ((byte)(148)),
        ((byte)(111)),
        ((byte)(212)),
        ((byte)(138)),
        ((byte)(20)),
        ((byte)(219)),
        ((byte)(244)),
        ((byte)(31)),
        ((byte)(73)),
        ((byte)(76)),
        ((byte)(28)),
        ((byte)(133)),
        ((byte)(57)),
        ((byte)(29)),
        ((byte)(163)),
        ((byte)(204)),
        ((byte)(190)),
        ((byte)(143)),
        ((byte)(26)),
        ((byte)(95)),
        ((byte)(191)),
        ((byte)(240)),
        ((byte)(67)),
        ((byte)(219)),
        ((byte)(139)),
        ((byte)(91)),
        ((byte)(38)),
        ((byte)(170)),
        ((byte)(235)),
        ((byte)(142)),
        ((byte)(81)),
        ((byte)(195)),
        ((byte)(229)),
        ((byte)(6)),
        ((byte)(65)),
        ((byte)(67)),
        ((byte)(98)),
        ((byte)(233)),
        ((byte)(218)),
        ((byte)(42)),
        ((byte)(77)),
        ((byte)(5)),
        ((byte)(2)),
        ((byte)(229)),
        ((byte)(172)),
        ((byte)(23)),
        ((byte)(140)),
        ((byte)(74)),
        ((byte)(104)),
        ((byte)(60)),
        ((byte)(210)),
        ((byte)(136)),
        ((byte)(249)),
        ((byte)(127)),
        ((byte)(7)),
        ((byte)(163)),
        ((byte)(43)),
        ((byte)(249)),
        ((byte)(254)),
        ((byte)(185)),
        ((byte)(181)),
        ((byte)(74)),
        ((byte)(52)),
        ((byte)(186)),
        ((byte)(250)),
        ((byte)(89)),
        ((byte)(160)),
        ((byte)(51)),
        ((byte)(220)),
        ((byte)(96)),
        ((byte)(105)),
        ((byte)(212)),
        ((byte)(180)),
        ((byte)(240)),
        ((byte)(18)),
        ((byte)(185)),
        ((byte)(238)),
        ((byte)(94)),
        ((byte)(46)),
        ((byte)(116)),
        ((byte)(206)),
        ((byte)(219)),
        ((byte)(65)),
        ((byte)(174)),
        ((byte)(188)),
        ((byte)(201)),
        ((byte)(202)),
        ((byte)(102)),
        ((byte)(255)),
        ((byte)(157)),
        ((byte)(23)),
        ((byte)(105)),
        ((byte)(235)),
        ((byte)(33)),
        ((byte)(117)),
        ((byte)(3)),
        ((byte)(209)),
        ((byte)(71)),
        ((byte)(234)),
        ((byte)(82)),
        ((byte)(119)),
        ((byte)(89)),
        ((byte)(110)),
        ((byte)(8)),
        ((byte)(211)),
        ((byte)(253)),
        ((byte)(211)),
        ((byte)(8)),
        ((byte)(109)),
        ((byte)(77)),
        ((byte)(180)),
        ((byte)(205)),
        ((byte)(202)),
        ((byte)(138)),
        ((byte)(234)),
        ((byte)(217)),
        ((byte)(9)),
        ((byte)(133)),
        ((byte)(254)),
        ((byte)(49)),
        ((byte)(143)),
        ((byte)(57)),
        ((byte)(51)),
        ((byte)(62)),
        ((byte)(72)),
        ((byte)(0)),
        ((byte)(233)),
        ((byte)(147)),
        ((byte)(123)),
        ((byte)(15)),
        ((byte)(232)),
        ((byte)(166)),
        ((byte)(115)),
        ((byte)(220)),
        ((byte)(253)),
        ((byte)(117)),
        ((byte)(109)),
        ((byte)(56)),
        ((byte)(219)),
        ((byte)(190)),
        ((byte)(246)),
        ((byte)(193)),
        ((byte)(249)),
        ((byte)(177)),
        ((byte)(232)),
        ((byte)(74)),
        ((byte)(158)),
        ((byte)(96)),
        ((byte)(54)),
        ((byte)(155)),
        ((byte)(249)),
        ((byte)(75)),
        ((byte)(73)),
        ((byte)(185)),
        ((byte)(195)),
        ((byte)(61)),
        ((byte)(37)),
        ((byte)(48)),
        ((byte)(191)),
        ((byte)(210)),
        ((byte)(20)),
        ((byte)(64)),
        ((byte)(140)),
        ((byte)(93)),
        ((byte)(101)),
        ((byte)(14)),
        ((byte)(89)),
        ((byte)(238)),
        ((byte)(141)),
        ((byte)(117)),
        ((byte)(108)),
        ((byte)(208)),
        ((byte)(170)),
        ((byte)(63)),
        ((byte)(59)),
        ((byte)(205)),
        ((byte)(64)),
        ((byte)(130)),
        ((byte)(85)),
        ((byte)(254)),
        ((byte)(98)),
        ((byte)(136)),
        ((byte)(92)),
        ((byte)(223)),
        ((byte)(21)),
        ((byte)(156)),
        ((byte)(93)),
        ((byte)(185)),
        ((byte)(24)),
        ((byte)(191)),
        ((byte)(79)),
        ((byte)(60)),
        ((byte)(121)),
        ((byte)(8)),
        ((byte)(170)),
        ((byte)(181)),
        ((byte)(52)),
        ((byte)(155)),
        ((byte)(75)),
        ((byte)(218)),
        ((byte)(240)),
        ((byte)(175)),
        ((byte)(211)),
        ((byte)(192)),
        ((byte)(47)),
        ((byte)(41)),
        ((byte)(160)),
        ((byte)(9)),
        ((byte)(126)),
        ((byte)(246)),
        ((byte)(253)),
        ((byte)(162)),
        ((byte)(218)),
        ((byte)(192)),
        ((byte)(112)),
        ((byte)(139)),
        ((byte)(227)),
        ((byte)(173)),
        ((byte)(72)),
        ((byte)(201)),
        ((byte)(176)),
        ((byte)(160)),
        ((byte)(214)),
        ((byte)(206)),
        ((byte)(38)),
        ((byte)(47)),
        ((byte)(87)),
        ((byte)(162)),
        ((byte)(149)),
        ((byte)(133)),
        ((byte)(152)),
        ((byte)(164)),
        ((byte)(55)),
        ((byte)(122)),
        ((byte)(14)),
        ((byte)(178)),
        ((byte)(181)),
        ((byte)(155)),
        ((byte)(176)),
        ((byte)(236)),
        ((byte)(251)),
        ((byte)(84)),
        ((byte)(59)),
        ((byte)(33)),
        ((byte)(193)),
        ((byte)(172)),
        ((byte)(97)),
        ((byte)(184)),
        ((byte)(151)),
        ((byte)(30)),
        ((byte)(209)),
        ((byte)(135)),
        ((byte)(83)),
        ((byte)(130)),
        ((byte)(42)),
        ((byte)(80)),
        ((byte)(217)),
        ((byte)(5)),
        ((byte)(154)),
        ((byte)(255)),
        ((byte)(209)),
        ((byte)(253)),
        ((byte)(115)),
        ((byte)(249)),
        ((byte)(94)),
        ((byte)(89)),
        ((byte)(107)),
        ((byte)(96)),
        ((byte)(178)),
        ((byte)(190)),
        ((byte)(213)),
        ((byte)(71)),
        ((byte)(252)),
        ((byte)(92)),
        ((byte)(205)),
        ((byte)(92)),
        ((byte)(100)),
        ((byte)(180)),
        ((byte)(12)),
        ((byte)(121)),
        ((byte)(205)),
        ((byte)(159)),
        ((byte)(11)),
        ((byte)(118)),
        ((byte)(179)),
        ((byte)(16)),
        ((byte)(81)),
        ((byte)(180)),
        ((byte)(79)),
        ((byte)(189)),
        ((byte)(216)),
        ((byte)(176)),
        ((byte)(1)),
        ((byte)(176)),
        ((byte)(26)),
        ((byte)(254)),
        ((byte)(224)),
        ((byte)(65)),
        ((byte)(195)),
        ((byte)(104)),
        ((byte)(64)),
        ((byte)(1)),
        ((byte)(5)),
        ((byte)(216)),
        ((byte)(73)),
        ((byte)(137)),
        ((byte)(139)),
        ((byte)(246)),
        ((byte)(181)),
        ((byte)(206)),
        ((byte)(235)),
        ((byte)(37)),
        ((byte)(248)),
        ((byte)(32)),
        ((byte)(50)),
        ((byte)(50)),
        ((byte)(242)),
        ((byte)(253)),
        ((byte)(69)),
        ((byte)(77)),
        ((byte)(7)),
        ((byte)(182)),
        ((byte)(17)),
        ((byte)(244)),
        ((byte)(230)),
        ((byte)(37)),
        ((byte)(70)),
        ((byte)(75)),
        ((byte)(65)),
        ((byte)(206)),
        ((byte)(123)),
        ((byte)(34)),
        ((byte)(240)),
        ((byte)(164)),
        ((byte)(57)),
        ((byte)(204)),
        ((byte)(153)),
        ((byte)(50)),
        ((byte)(45)),
        ((byte)(41)),
        ((byte)(133)),
        ((byte)(90)),
        ((byte)(255)),
        ((byte)(129)),
        ((byte)(210)),
        ((byte)(178)),
        ((byte)(183)),
        ((byte)(224)),
        ((byte)(126)),
        ((byte)(232)),
        ((byte)(11)),
        ((byte)(227)),
        ((byte)(252)),
        ((byte)(118)),
        ((byte)(96)),
        ((byte)(137)),
        ((byte)(240)),
        ((byte)(16)),
        ((byte)(242)),
        ((byte)(35)),
        ((byte)(67)),
        ((byte)(63)),
        ((byte)(181)),
        ((byte)(230)),
        ((byte)(83)),
        ((byte)(200)),
        ((byte)(53)),
        ((byte)(84)),
        ((byte)(231)),
        ((byte)(102)),
        ((byte)(152)),
        ((byte)(191)),
        ((byte)(207)),
        ((byte)(27)),
        ((byte)(200)),
        ((byte)(173)),
        ((byte)(183)),
        ((byte)(143)),
        ((byte)(34)),
        ((byte)(51)),
        ((byte)(110)),
        ((byte)(102)),
        ((byte)(205)),
        ((byte)(88)),
        ((byte)(195)),
        ((byte)(152)),
        ((byte)(38)),
        ((byte)(121)),
        ((byte)(67)),
        ((byte)(175)),
        ((byte)(219)),
        ((byte)(137)),
        ((byte)(64)),
        ((byte)(9)),
        ((byte)(230)),
        ((byte)(69)),
        ((byte)(164)),
        ((byte)(24)),
        ((byte)(45)),
        ((byte)(9)),
        ((byte)(124)),
        ((byte)(98)),
        ((byte)(248)),
        ((byte)(23)),
        ((byte)(80)),
        ((byte)(75)),
        ((byte)(19)),
        ((byte)(224)),
        ((byte)(174)),
        ((byte)(179)),
        ((byte)(210)),
        ((byte)(96)),
        ((byte)(237)),
        ((byte)(190)),
        ((byte)(181)),
        ((byte)(221)),
        ((byte)(114)),
        ((byte)(93)),
        ((byte)(35)),
        ((byte)(186)),
        ((byte)(162)),
        ((byte)(188)),
        ((byte)(17)),
        ((byte)(56)),
        ((byte)(138)),
        ((byte)(14)),
        ((byte)(127)),
        ((byte)(198)),
        ((byte)(53)),
        ((byte)(130)),
        ((byte)(8)),
        ((byte)(158)),
        ((byte)(98)),
        ((byte)(24)),
        ((byte)(183)),
        ((byte)(11)),
        ((byte)(109)),
        ((byte)(181)),
        ((byte)(7)),
        ((byte)(119)),
        ((byte)(132)),
        ((byte)(69)),
        ((byte)(202)),
        ((byte)(143)),
        ((byte)(221)),
        ((byte)(123)),
        ((byte)(155)),
        ((byte)(130)),
        ((byte)(83)),
        ((byte)(9)),
        ((byte)(211)),
        ((byte)(71)),
        ((byte)(245)),
        ((byte)(115)),
        ((byte)(103)),
        ((byte)(192)),
        ((byte)(81)),
        ((byte)(192)),
        ((byte)(140)),
        ((byte)(66)),
        ((byte)(204)),
        ((byte)(77)),
        ((byte)(171)),
        ((byte)(44)),
        ((byte)(171)),
        ((byte)(51)),
        ((byte)(254)),
        ((byte)(212)),
        ((byte)(6)),
        ((byte)(170)),
        ((byte)(111)),
        ((byte)(188)),
        ((byte)(85)),
        ((byte)(171)),
        ((byte)(53)),
        ((byte)(92)),
        ((byte)(241)),
        ((byte)(129)),
        ((byte)(90)),
        ((byte)(15)),
        ((byte)(115)),
        ((byte)(253)),
        ((byte)(114)),
        ((byte)(43)),
        ((byte)(175)),
        ((byte)(192)),
        ((byte)(169)),
        ((byte)(238)),
        ((byte)(177)),
        ((byte)(247)),
        ((byte)(185)),
        ((byte)(173)),
        ((byte)(41)),
        ((byte)(197)),
        ((byte)(170)),
        ((byte)(55)),
        ((byte)(154)),
        ((byte)(158)),
        ((byte)(228)),
        ((byte)(170)),
        ((byte)(125)),
        ((byte)(198)),
        ((byte)(123)),
        ((byte)(169)),
        ((byte)(153)),
        ((byte)(22)),
        ((byte)(241)),
        ((byte)(73)),
        ((byte)(61)),
        ((byte)(10)),
        ((byte)(206)),
        ((byte)(208)),
        ((byte)(101)),
        ((byte)(125)),
        ((byte)(207)),
        ((byte)(207)),
        ((byte)(218)),
        ((byte)(127)),
        ((byte)(124)),
        ((byte)(234)),
        ((byte)(137)),
        ((byte)(15)),
        ((byte)(35)),
        ((byte)(15)),
        ((byte)(240)),
        ((byte)(194)),
        ((byte)(146)),
        ((byte)(144)),
        ((byte)(1)),
        ((byte)(253)),
        ((byte)(194)),
        ((byte)(83)),
        ((byte)(156)),
        ((byte)(176)),
        ((byte)(146)),
        ((byte)(172)),
        ((byte)(129)),
        ((byte)(200)),
        ((byte)(145)),
        ((byte)(152)),
        ((byte)(207)),
        ((byte)(95)),
        ((byte)(177)),
        ((byte)(166)),
        ((byte)(41)),
        ((byte)(233)),
        ((byte)(71)),
        ((byte)(172)),
        ((byte)(246)),
        ((byte)(218)),
        ((byte)(93)),
        ((byte)(26)),
        ((byte)(33)),
        ((byte)(250)),
        ((byte)(32)),
        ((byte)(109)),
        ((byte)(163)),
        ((byte)(107)),
        ((byte)(184)),
        ((byte)(215)),
        ((byte)(132)),
        ((byte)(96)),
        ((byte)(72)),
        ((byte)(63)),
        ((byte)(72)),
        ((byte)(123)),
        ((byte)(52)),
        ((byte)(180)),
        ((byte)(234)),
        ((byte)(34)),
        ((byte)(77)),
        ((byte)(17)),
        ((byte)(237)),
        ((byte)(228)),
        ((byte)(26)),
        ((byte)(42)),
        ((byte)(93)),
        ((byte)(125)),
        ((byte)(230)),
        ((byte)(7)),
        ((byte)(122)),
        ((byte)(230)),
        ((byte)(154)),
        ((byte)(38)),
        ((byte)(160)),
        ((byte)(168)),
        ((byte)(49)),
        ((byte)(161)),
        ((byte)(144)),
        ((byte)(36)),
        ((byte)(9)),
        ((byte)(22)),
        ((byte)(16)),
        ((byte)(186)),
        ((byte)(20)),
        ((byte)(110)),
        ((byte)(23)),
        ((byte)(114)),
        ((byte)(93)),
        ((byte)(173)),
        ((byte)(180)),
        ((byte)(147)),
        ((byte)(193)),
        ((byte)(211)),
        ((byte)(141)),
        ((byte)(75)),
        ((byte)(44)),
        ((byte)(61)),
        ((byte)(223)),
        ((byte)(245)),
        ((byte)(15)),
        ((byte)(37)),
        ((byte)(133)),
        ((byte)(177)),
        ((byte)(93)),
        ((byte)(157)),
        ((byte)(198)),
        ((byte)(33)),
        ((byte)(158)),
        ((byte)(160)),
        ((byte)(73)),
        ((byte)(146)),
        ((byte)(36)),
        ((byte)(197)),
        ((byte)(25)),
        ((byte)(55)),
        ((byte)(1)),
        ((byte)(51)),
        ((byte)(208)),
        ((byte)(171)),
        ((byte)(18)),
        ((byte)(235)),
        ((byte)(31)),
        ((byte)(56)),
        ((byte)(82)),
        ((byte)(231)),
        ((byte)(36)),
        ((byte)(198)),
        ((byte)(153)),
        ((byte)(85)),
        ((byte)(123)),
        ((byte)(244)),
        ((byte)(193)),
        ((byte)(154)),
        ((byte)(21)),
        ((byte)(227)),
        ((byte)(145)),
        ((byte)(94)),
        ((byte)(92)),
        ((byte)(118)),
        ((byte)(168)),
        ((byte)(245)),
        ((byte)(211)),
        ((byte)(189)),
        ((byte)(100)),
        ((byte)(34)),
        ((byte)(110)),
        ((byte)(252)),
        ((byte)(185)),
        ((byte)(85)),
        ((byte)(73)),
        ((byte)(248)),
        ((byte)(108)),
        ((byte)(52)),
        ((byte)(227)),
        ((byte)(35)),
        ((byte)(6)),
        ((byte)(76)),
        ((byte)(94)),
        ((byte)(117)),
        ((byte)(120)),
        ((byte)(255)),
        ((byte)(136)),
        ((byte)(73)),
        ((byte)(36)),
        ((byte)(85)),
        ((byte)(208)),
        ((byte)(137)),
        ((byte)(176)),
        ((byte)(54)),
        ((byte)(166)),
        ((byte)(162)),
        ((byte)(215)),
        ((byte)(89)),
        ((byte)(3)),
        ((byte)(29)),
        ((byte)(24)),
        ((byte)(97)),
        ((byte)(212)),
        ((byte)(48)),
        ((byte)(120)),
        ((byte)(40)),
        ((byte)(13)),
        ((byte)(67)),
        ((byte)(11)),
        ((byte)(131)),
        ((byte)(135)),
        ((byte)(141)),
        ((byte)(183)),
        ((byte)(241)),
        ((byte)(220)),
        ((byte)(68)),
        ((byte)(0)),
        ((byte)(230)),
        ((byte)(254)),
        ((byte)(168)),
        ((byte)(108)),
        ((byte)(137)),
        ((byte)(152)),
        ((byte)(15)),
        ((byte)(82)),
        ((byte)(229)),
        ((byte)(76)),
        ((byte)(131)),
        ((byte)(175)),
        ((byte)(166)),
        ((byte)(33)),
        ((byte)(19)),
        ((byte)(49)),
        ((byte)(198)),
        ((byte)(11)),
        ((byte)(164)),
        ((byte)(120)),
        ((byte)(46)),
        ((byte)(253)),
        ((byte)(79)),
        ((byte)(242)),
        ((byte)(69)),
        ((byte)(61)),
        ((byte)(161)),
        ((byte)(205)),
        ((byte)(66)),
        ((byte)(210)),
        ((byte)(190)),
        ((byte)(89)),
        ((byte)(97)),
        ((byte)(162)),
        ((byte)(240)),
        ((byte)(90)),
        ((byte)(90)),
        ((byte)(176)),
        ((byte)(142)),
        ((byte)(201)),
        ((byte)(196)),
        ((byte)(221)),
        ((byte)(146)),
        ((byte)(220)),
        ((byte)(137)),
        ((byte)(147)),
        ((byte)(100)),
        ((byte)(97)),
        ((byte)(115)),
        ((byte)(92)),
        ((byte)(241)),
        ((byte)(230)),
        ((byte)(56)),
        ((byte)(204)),
        ((byte)(210)),
        ((byte)(233)),
        ((byte)(174)),
        ((byte)(182)),
        ((byte)(39)),
        ((byte)(76)),
        ((byte)(247)),
        ((byte)(65)),
        ((byte)(15)),
        ((byte)(19)),
        ((byte)(141)),
        ((byte)(41)),
        ((byte)(78)),
        ((byte)(4)),
        ((byte)(49)),
        ((byte)(184)),
        ((byte)(214)),
        ((byte)(22)),
        ((byte)(124)),
        ((byte)(219)),
        ((byte)(179)),
        ((byte)(80)),
        ((byte)(106)),
        ((byte)(114)),
        ((byte)(104)),
        ((byte)(178)),
        ((byte)(217)),
        ((byte)(63)),
        ((byte)(90)),
        ((byte)(230)),
        ((byte)(225)),
        ((byte)(216)),
        ((byte)(33)),
        ((byte)(149)),
        ((byte)(208)),
        ((byte)(6)),
        ((byte)(171)),
        ((byte)(163)),
        ((byte)(136)),
        ((byte)(66)),
        ((byte)(209)),
        ((byte)(131)),
        ((byte)(206)),
        ((byte)(127)),
        ((byte)(79)),
        ((byte)(96)),
        ((byte)(69)),
        ((byte)(96)),
        ((byte)(48)),
        ((byte)(186)),
        ((byte)(133)),
        ((byte)(218)),
        ((byte)(105)),
        ((byte)(92)),
        ((byte)(24)),
        ((byte)(129)),
        ((byte)(126)),
        ((byte)(59)),
        ((byte)(77)),
        ((byte)(116)),
        ((byte)(114)),
        ((byte)(183)),
        ((byte)(231)),
        ((byte)(41)),
        ((byte)(50)),
        ((byte)(181)),
        ((byte)(8)),
        ((byte)(184)),
        ((byte)(52)),
        ((byte)(42)),
        ((byte)(13)),
        ((byte)(50)),
        ((byte)(141)),
        ((byte)(58)),
        ((byte)(9)),
        ((byte)(47)),
        ((byte)(130)),
        ((byte)(234)),
        ((byte)(35)),
        ((byte)(8)),
        ((byte)(109)),
        ((byte)(121)),
        ((byte)(15)),
        ((byte)(159)),
        ((byte)(96)),
        ((byte)(6)),
        ((byte)(110)),
        ((byte)(196)),
        ((byte)(124)),
        ((byte)(78)),
        ((byte)(135)),
        ((byte)(111)),
        ((byte)(86)),
        ((byte)(19)),
        ((byte)(207)),
        ((byte)(25)),
        ((byte)(156)),
        ((byte)(165)),
        ((byte)(77)),
        ((byte)(153)),
        ((byte)(88)),
        ((byte)(140)),
        ((byte)(43)),
        ((byte)(6)),
        ((byte)(173)),
        ((byte)(83)),
        ((byte)(77)),
        ((byte)(47)),
        ((byte)(83)),
        ((byte)(232)),
        ((byte)(255)),
        ((byte)(148)),
        ((byte)(23)),
        ((byte)(69)),
        ((byte)(7)),
        ((byte)(249)),
        ((byte)(168)),
        ((byte)(71)),
        ((byte)(200)),
        ((byte)(43)),
        ((byte)(71)),
        ((byte)(67)),
        ((byte)(60)),
        ((byte)(230)),
        ((byte)(162)),
        ((byte)(157)),
        ((byte)(220)),
        ((byte)(121)),
        ((byte)(106)),
        ((byte)(239)),
        ((byte)(147)),
        ((byte)(221)),
        ((byte)(157)),
        ((byte)(138)),
        ((byte)(176)),
        ((byte)(225)),
        ((byte)(77)),
        ((byte)(9)),
        ((byte)(241)),
        ((byte)(13)),
        ((byte)(184)),
        ((byte)(62)),
        ((byte)(113)),
        ((byte)(147)),
        ((byte)(79)),
        ((byte)(243)),
        ((byte)(88)),
        ((byte)(17)),
        ((byte)(12)),
        ((byte)(213)),
        ((byte)(113)),
        ((byte)(84)),
        ((byte)(220)),
        ((byte)(33)),
        ((byte)(82)),
        ((byte)(20)),
        ((byte)(79)),
        ((byte)(69)),
        ((byte)(99)),
        ((byte)(16)),
        ((byte)(118)),
        ((byte)(212)),
        ((byte)(196)),
        ((byte)(99)),
        ((byte)(85)),
        ((byte)(34)),
        ((byte)(246)),
        ((byte)(141)),
        ((byte)(148)),
        ((byte)(38)),
        ((byte)(172)),
        ((byte)(159)),
        ((byte)(86)),
        ((byte)(187)),
        ((byte)(115)),
        ((byte)(8)),
        ((byte)(209)),
        ((byte)(168)),
        ((byte)(150)),
        ((byte)(174)),
        ((byte)(69)),
        ((byte)(203)),
        ((byte)(109)),
        ((byte)(148)),
        ((byte)(126)),
        ((byte)(63)),
        ((byte)(0)),
        ((byte)(123)),
        ((byte)(56)),
        ((byte)(156)),
        ((byte)(145)),
        ((byte)(8)),
        ((byte)(165)),
        ((byte)(225)),
        ((byte)(150)),
        ((byte)(228)),
        ((byte)(121)),
        ((byte)(14)),
        ((byte)(62)),
        ((byte)(44)),
        ((byte)(252)),
        ((byte)(202)),
        ((byte)(124)),
        ((byte)(229)),
        ((byte)(41)),
        ((byte)(209)),
        ((byte)(254)),
        ((byte)(33)),
        ((byte)(174)),
        ((byte)(73)),
        ((byte)(66)),
        ((byte)(166)),
        ((byte)(174)),
        ((byte)(180)),
        ((byte)(203)),
        ((byte)(171)),
        ((byte)(102)),
        ((byte)(48)),
        ((byte)(228)),
        ((byte)(21)),
        ((byte)(33)),
        ((byte)(123)),
        ((byte)(85)),
        ((byte)(248)),
        ((byte)(149)),
        ((byte)(164)),
        ((byte)(250)),
        ((byte)(116)),
        ((byte)(36)),
        ((byte)(142)),
        ((byte)(142)),
        ((byte)(195)),
        ((byte)(106)),
        ((byte)(106)),
        ((byte)(178)),
        ((byte)(122)),
        ((byte)(78)),
        ((byte)(135)),
        ((byte)(107)),
        ((byte)(173)),
        ((byte)(65)),
        ((byte)(223)),
        ((byte)(205)),
        ((byte)(238)),
        ((byte)(89)),
        ((byte)(234)),
        ((byte)(89)),
        ((byte)(241)),
        ((byte)(22)),
        ((byte)(235)),
        ((byte)(125)),
        ((byte)(73)),
        ((byte)(41)),
        ((byte)(40)),
        ((byte)(10)),
        ((byte)(129)),
        ((byte)(116)),
        ((byte)(132)),
        ((byte)(80)),
        ((byte)(133)),
        ((byte)(215)),
        ((byte)(137)),
        ((byte)(252)),
        ((byte)(31)),
        ((byte)(187)),
        ((byte)(127)),
        ((byte)(60)),
        ((byte)(68)),
        ((byte)(2)),
        ((byte)(80)),
        ((byte)(93)),
        ((byte)(223)),
        ((byte)(196)),
        ((byte)(55)),
        ((byte)(212)),
        ((byte)(66)),
        ((byte)(174)),
        ((byte)(103)),
        ((byte)(159)),
        ((byte)(171)),
        ((byte)(74)),
        ((byte)(9)),
        ((byte)(94)),
        ((byte)(57)),
        ((byte)(17)),
        ((byte)(68)),
        ((byte)(153)),
        ((byte)(66)),
        ((byte)(95)),
        ((byte)(48)),
        ((byte)(5)),
        ((byte)(201)),
        ((byte)(55)),
        ((byte)(230)),
        ((byte)(213)),
        ((byte)(184)),
        ((byte)(227)),
        ((byte)(173)),
        ((byte)(50)),
        ((byte)(218)),
        ((byte)(173)),
        ((byte)(21)),
        ((byte)(238)),
        ((byte)(197)),
        ((byte)(141)),
        ((byte)(158)),
        ((byte)(133)),
        ((byte)(241)),
        ((byte)(83)),
        ((byte)(200)),
        ((byte)(211)),
        ((byte)(13)),
        ((byte)(229)),
        ((byte)(165)),
        ((byte)(58)),
        ((byte)(206)),
        ((byte)(42)),
        ((byte)(194)),
        ((byte)(14)),
        ((byte)(118)),
        ((byte)(229)),
        ((byte)(249)),
        ((byte)(229)),
        ((byte)(209)),
        ((byte)(74)),
        ((byte)(147)),
        ((byte)(168)),
        ((byte)(222)),
        ((byte)(97)),
        ((byte)(28)),
        ((byte)(94)),
        ((byte)(1)),
        ((byte)(52)),
        ((byte)(196)),
        ((byte)(253)),
        ((byte)(53)),
        ((byte)(26)),
        ((byte)(153)),
        ((byte)(171)),
        ((byte)(115)),
        ((byte)(191)),
        ((byte)(168)),
        ((byte)(238)),
        ((byte)(150)),
        ((byte)(93)),
        ((byte)(248)),
        ((byte)(228)),
        ((byte)(146)),
        ((byte)(171)),
        ((byte)(7)),
        ((byte)(141)),
        ((byte)(32)),
        ((byte)(159)),
        ((byte)(188)),
        ((byte)(245)),
        ((byte)(180)),
        ((byte)(48)),
        ((byte)(28)),
        ((byte)(122)),
        ((byte)(250)),
        ((byte)(245)),
        ((byte)(166)),
        ((byte)(144)),
        ((byte)(55)),
        ((byte)(105)),
        ((byte)(210)),
        ((byte)(217)),
        ((byte)(32)),
        ((byte)(167)),
        ((byte)(4)),
        ((byte)(179)),
        ((byte)(145)),
        ((byte)(23)),
        ((byte)(155)),
        ((byte)(183)),
        ((byte)(61)),
        ((byte)(11)),
        ((byte)(78)),
        ((byte)(116)),
        ((byte)(82)),
        ((byte)(174)),
        ((byte)(22)),
        ((byte)(50)),
        ((byte)(90)),
        ((byte)(143)),
        ((byte)(62)),
        ((byte)(97)),
        ((byte)(120)),
        ((byte)(207)),
        ((byte)(73)),
        ((byte)(5)),
        ((byte)(254)),
        ((byte)(30)),
        ((byte)(177)),
        ((byte)(125)),
        ((byte)(24)),
        ((byte)(24)),
        ((byte)(183)),
        ((byte)(44)),
        ((byte)(139)),
        ((byte)(31)),
        ((byte)(195)),
        ((byte)(234)),
        ((byte)(166)),
        ((byte)(83)),
        ((byte)(252)),
        ((byte)(9)),
        ((byte)(4)),
        ((byte)(4)),
        ((byte)(184)),
        ((byte)(169)),
        ((byte)(225)),
        ((byte)(168)),
        ((byte)(40)),
        ((byte)(75)),
        ((byte)(223)),
        ((byte)(116)),
        ((byte)(53)),
        ((byte)(168)),
        ((byte)(43)),
        ((byte)(112)),
        ((byte)(96)),
        ((byte)(81)),
        ((byte)(94)),
        ((byte)(255)),
        ((byte)(181)),
        ((byte)(115)),
        ((byte)(101)),
        ((byte)(29)),
        ((byte)(158)),
        ((byte)(37)),
        ((byte)(83)),
        ((byte)(34)),
        ((byte)(232)),
        ((byte)(50)),
        ((byte)(234)),
        ((byte)(43)),
        ((byte)(139)),
        ((byte)(6)),
        ((byte)(146)),
        ((byte)(53)),
        ((byte)(93)),
        ((byte)(115))};
            this.hex21.Dock = System.Windows.Forms.DockStyle.Fill;
            this.hex21.Font = new System.Drawing.Font("Courier New", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.hex21.Location = new System.Drawing.Point(0, 0);
            this.hex21.Name = "hex21";
            this.hex21.Size = new System.Drawing.Size(543, 343);
            this.hex21.TabIndex = 0;
            // 
            // FormTest2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(736, 343);
            this.Controls.Add(this.hex21);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FormTest2";
            this.Text = "Base10";
            this.Load += new System.EventHandler(this.FormTest2_Load);
            this.panel1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Hex2 hex21;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label lblByte;
        private System.Windows.Forms.Label lblInt32;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lblUint16;
        private System.Windows.Forms.Label lblInt16;
        private System.Windows.Forms.Label lblUint32;
        private System.Windows.Forms.Label lblFloat;
        private System.Windows.Forms.Label label7;
    }
}